### ISSUE TITLE
Put in the Readme what the APP ID is and how to get it.

### ISSUE THREAD

**Issue by AraHaan** [simmsb/discord-emacs.el#1]
It would be nice if it describes how to get the App ID and what it is

**Comment by simmsb** [comment]
Done.

**Comment by AraHaan** [comment]
Thanks, Also following that it seems how I got this:

```
Loading e:/Users/Elsword/Desktop/emacs-25.3-i686/bin/emacs-rich-presence.elc...
Loading e:/Users/Elsword/Desktop/emacs-25.3-i686/bin/discord-emacs.el (source)...done
make-ipc-connection: Malformed :address
```

**Comment by simmsb** [comment]
I haven't added support for windows yet, the socket address is at `"\\\\?\\pipe\\discord-ipc-0"` for windows and it might work to just replace the address. I'll get windows support added tomorrow when I have access to a Windows device to test on.

**Comment by AraHaan** [comment]
Alright, I guess I could test it in the mean time.

**Comment by simmsb** [comment]
Unfortunately, I've not been able to get a windows connection working.
