### ISSUE TITLE
What languages are supported?

### ISSUE THREAD

**Issue by jeetelongname** [simmsb/discord-emacs.el#11]
I have been using this extension (which I am having a lot of fun with) and I was just wondering what languages are actually supported because it seems like a lot more than what the README sets out. Thanks in advance!

**Comment by simmsb** [comment]
You're free to create your own rich presence application with your own assets, the one given in the example has the following assets: 
![image](https://user-images.githubusercontent.com/5330444/91354035-fc050000-e7e3-11ea-97e9-3cf544ee13cc.png)

There's also another application that uses atom's icons (472881182770724874): 
![image](https://user-images.githubusercontent.com/5330444/91354225-4c7c5d80-e7e4-11ea-9dda-5df315542124.png)
![image](https://user-images.githubusercontent.com/5330444/91354283-661da500-e7e4-11ea-9f23-0f5748ef6d44.png)

**Comment by jeetelongname** [comment]
I am just checking (I don't use discord all that much) but all I would need to do is add the icons and name it that language that it represents? Would there be anything more I would need to do?

**Comment by simmsb** [comment]
Yeah, the file extension is what's used to select the image to display.

**Comment by jeetelongname** [comment]
Perfect. Thanks for your help! I'll start playing around with this! I'll close the issue now.
