### ISSUE TITLE
Create and enhance images for Rich Presence

### ISSUE THREAD

**Issue by ghost** [simmsb/discord-emacs.el#13]
[NewLogos.tar.gz](https://github.com/simmsb/discord-emacs.el/files/6580612/NewLogos.tar.gz)

**Comment by simmsb** [comment]
Rich presence assets need to be at least 512x512 pixels.

These look alright though so I'll replace them if you can get 512x512 images.

**Comment by ghost** [comment]
[Logo.tar.gz](https://github.com/simmsb/discord-emacs.el/files/6586889/Logo.tar.gz)

**Comment by simmsb** [comment]
Looks good, thanks
![image](https://user-images.githubusercontent.com/5330444/120567229-2934ad80-c409-11eb-8c68-fb81f12ef74f.png)
