### ISSUE TITLE
No such file or directory for ipc process

### ISSUE THREAD

**Issue by jazzychad** [simmsb/discord-emacs.el#15]
When I run `(discord-emacs-run "384815451978334208")` I get the following error in the minibuffer:

```
Error in post-command-hook (discord-emacs--ipc-send-update): (file-missing "make client process failed" "No such file or directory" :name "discord-ipc-process" :remote "/run/user/501/discord-ipc-0")
```

Running on an M1 macbook pro, macOS 11.3.1
emacs 27.2-2

**Comment by jazzychad** [comment]
Same if i set `discord-emacs-ipc-dir` to some existing path on my disk like `~/ipc/`

**Comment by simmsb** [comment]
Can you find where discord creates it's ipc socket on your system/ macos?

On linux it's usually `/run/user/<uid>/discord-ipc-0`.

**Comment by jazzychad** [comment]
Ohhh I see. Yes, it's buried in some very strange tmp file folder each time the process is run (macOS sandboxing thing). Ok, I will have to figure out how to deal with this, but at least I got it working! Thank you.
