### ISSUE TITLE
no such file discord-ipc-0

### ISSUE THREAD

**Issue by 0xameer** [simmsb/discord-emacs.el#16]
![dicsord](https://user-images.githubusercontent.com/847157/147585357-0d9cb5c6-ddfc-4020-ba61-e6d3f934a481.jpg)

**Comment by simmsb** [comment]
I'm guessing the ipc file isn't in the usual place, you'll want to customize `discord-emacs-ipc-dir` and `discord-emacs-ipc-name` to match up with the correct location.

**Comment by ItsNilDev** [comment]
@simmsb can you enlighten us for a fix on this error?
